/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.UsuarioDAO;
import DTO.Usuario_logado;
import DTO.usuario;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSetMetaData;
import javax.swing.ImageIcon;

/**
 *
 * @author will
 */
public class loginView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginView.class.getName());

    private char echoOriginal;

    Connection conexao = null;
    ResultSetMetaData rs = null;

    /**
     * Creates new form loginView
     */
    public loginView() {
        initComponents();

        echoOriginal = Senhatxt.getEchoChar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        OcultarSenha = new javax.swing.JCheckBox();
        Senhatxt = new javax.swing.JPasswordField();
        Usuariotxt = new javax.swing.JTextField();
        Entrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel2.setText("Gmail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 116, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 156, -1, -1));

        OcultarSenha.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        OcultarSenha.setText("Mostrar");
        OcultarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcultarSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(OcultarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 184, -1, -1));

        Senhatxt.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Senhatxt.setSelectionColor(new java.awt.Color(255, 255, 0));
        Senhatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhatxtActionPerformed(evt);
            }
        });
        getContentPane().add(Senhatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 155, 200, -1));

        Usuariotxt.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Usuariotxt.setSelectionColor(new java.awt.Color(255, 255, 51));
        Usuariotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariotxtActionPerformed(evt);
            }
        });
        getContentPane().add(Usuariotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 115, 200, -1));

        Entrar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        getContentPane().add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 229, 100, 48));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel4.setText("Sem conta?");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 292, -1, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton1.setText("Cadastro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 316, -1, 24));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OcultarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcultarSenhaActionPerformed
        // TODO add your handling code here:
        if (OcultarSenha.isSelected()) {
            Senhatxt.setEchoChar((char) 0);
            OcultarSenha.setText("ocultar");
        } else {
            Senhatxt.setEchoChar(echoOriginal);
            OcultarSenha.setText("mostrar");
        }
    }//GEN-LAST:event_OcultarSenhaActionPerformed

    private void UsuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariotxtActionPerformed

    private void SenhatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SenhatxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cadastroView tela = new cadastroView();

        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
       
        usuario objlogindto = new usuario();

        String usuario, Senha;

        usuario = Usuariotxt.getText();
        Senha = Senhatxt.getText();

        objlogindto.setGmail(usuario);
        objlogindto.setSenha(Senha);

        UsuarioDAO objlogindao = new UsuarioDAO();

        if (objlogindao.autenticar(objlogindto) == true) {
            NewJFrame tela = new NewJFrame();
            tela.setVisible(true);
            this.dispose();
            
        }
    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrar;
    private javax.swing.JCheckBox OcultarSenha;
    private javax.swing.JPasswordField Senhatxt;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
